### ISSUE TITLE
Android support? 

### ISSUE THREAD

**Issue by bkchr** [gliheng/flutter-rs#1]
Hey any plan on supporting Android as well?

**Comment by gliheng** [comment]
The official flutter runs on android. Why not just use that?

**Comment by bkchr** [comment]
Because I have an app with a rust core and the rest is written in Kotlin. I would like to write as much as possible in rust :)

**Comment by gliheng** [comment]
I'm currently focusing on supporting desktop platforms. The idea of supporting all platform sounds good, but maybe need tremendous amount of work. However PR is welcome if you could work it out. ( ¨̮ )

**Comment by bkchr** [comment]
Okay :)

**Comment by balthild** [comment]
You can use platform channels to invoke JNI calls in Flutter Android.

**Comment by bkchr** [comment]
@balthild yeah I know, but for that I need to write another layer of Kotlin/Java to call into rust.

**Comment by balthild** [comment]
@bkchr This might help you: https://github.com/dart-lang/sdk/issues/34452

**Comment by bkchr** [comment]
Yeah I know this issue, but that does not solve my problem^^
