### ISSUE TITLE
Cannot build example on mac Mojave

### ISSUE THREAD

**Issue by tommaso1** [gliheng/flutter-rs#13]
I recently uodated my mac and even the example does not work anymore
when i `./run.py` it says: 

```error[E0432]: unresolved import `core_foundation`
  --> flutter-app-demo/rust/src/main.rs:20:5
   |
20 | use core_foundation::bundle;
   |     ^^^^^^^^^^^^^^^ use of undeclared type or module `core_foundation`
```

**Comment by gliheng** [comment]
Hi, tommaso1. Thank you for your feedback. I've fixed the issue. Try the master branch.
