### ISSUE TITLE
[Question] Possible to expose glutin/GL for 3D graphics

### ISSUE THREAD

**Issue by JoeHowarth** [gliheng/flutter-rs#34]
I'm trying to draw a 3D map for a mostly UI simulation, is this possible currently? If not, do you see this being added at some point?

Thanks

**Comment by 999eagle** [comment]
Right now this isn't possible in Rust as your code would have to render something every frame, but the current window loop doesn't have any kind of callback to allow that. A callback like this would be easily added though.
It is possible though to render 3D objects in pure Dart though inside your flutter app, see [this](https://github.com/hemanthrajv/flutter_3d_obj) flutter plugin.
