### ISSUE TITLE
Text doesn't show up in example

### ISSUE THREAD

**Issue by glesica** [gliheng/flutter-rs#4]
I suspect that this is a missing library, but I'm not sure which one. When I run the example app (https://github.com/gliheng/flutter-app-template) I see this:

![flutter-desktop-no-text](https://user-images.githubusercontent.com/165338/52393720-9962dc80-2a64-11e9-9204-2691cea85a0d.png)

Everything is there except the text. Any suggestions? I'm on Ubuntu 18.10. I installed the following dependencies to get the Python script to work:

  * libglfw3
  * cmake
  * libxrandr-dev
  * libxcb-xinerama0-dev
  * libxinerama-dev
  * libxcursor-dev
  * freeglut3-dev
  * libxi-dev

**Comment by est31** [comment]
Dunno, it works for me on Kubuntu 18.10

**Comment by est31** [comment]
Actually, disregard that. For me it seems to miss rendering the DEBUG in the top right corner, but the text in the center is fine.

![screenshot_20190207_085733](https://user-images.githubusercontent.com/8872119/52397604-68ab9300-2ab6-11e9-8494-7c6260b06009.png)

How it's supposed to be:

![supposed to be](https://raw.githubusercontent.com/gliheng/flutter-rs/master/www/images/screenshot_mac.png)

**Comment by gliheng** [comment]
I came into this issue on ubuntu18. Currently, there's a workaround. Swith debugDefaultPlatformOverride to fuchia seem to fix it.

**Comment by glesica** [comment]
Hmm, doesn't seem to make a difference on my machine.

**Comment by 999eagle** [comment]
Okay we've had very similar issue in running a flutter app on Desktop. It seems that this is a problem of font matching, sometimes no font is found for texts. I've had multiple people test it on their various Linux systems and while we didn't find the reason for this issue, we found a solution:
You have to add a default font to `pubspec.yaml` for the family `''` like this:
```yaml
    - family: ''
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
```
Of course the font asset itself has to exist.
Solution is based on this issue: https://github.com/google/flutter-desktop-embedding/issues/212

**Comment by gliheng** [comment]
@999eagle  Yes, it's duel to missing font problem. I've fixed the example by using default font ubuntu on linux. In real project, embed font should be considered.
