### ISSUE TITLE
flutter-download download uri maybe wrong

### ISSUE THREAD

**Issue by gliheng** [gliheng/flutter-rs#44]
I just found that we might have downloaded flutter-engine from the wrong url on beta.

This url is current used,
https://storage.flutter-io.cn/flutter_infra/flutter/52c7a1e849a170be4b2b2fe34142ca2c0a6fea1f/linux-x64/linux-x64-flutter.zip

But as I found, this zip does not contain `flutter_embeder.h`. I think this binary contains embeder, glfw and other stuff and might be google's final desktop runner.

According to google's wiki, we might use for only embedder, like this one:
https://storage.flutter-io.cn/flutter_infra/flutter/52c7a1e849a170be4b2b2fe34142ca2c0a6fea1f/linux-x64/linux-x64-embedder

**Comment by 999eagle** [comment]
The new download contains both the desktop shell and the embedder API. Sadly there is no download that contains both the new and the old headers, so for now I've opted to download the new library and headers and manually added the old headers.

**Comment by gliheng** [comment]
I mean the Old downloads are still available and contain the Old header only. We can continue to use them. New package are probably for Google desktop  implementation. We probably dont need them.

**Comment by gliheng** [comment]
I've fixed the download url in https://github.com/gliheng/flutter-rs/commit/e58866f12aaeb5bff5f01e0068a8c64500468eab    Is it working for you?

**Comment by 999eagle** [comment]
Okay, works fine as well. I'll close this :)
