### ISSUE TITLE
window initially black

### ISSUE THREAD

**Issue by gliheng** [gliheng/flutter-rs#49]
After window is opened, before engine starts, there's a blink of black color.

**Comment by gliheng** [comment]
Sovled with https://github.com/gliheng/flutter-rs/commit/3f1da8f3b196e7a75b02c8dd232dccf0f2a0f213

**Comment by 999eagle** [comment]
This change leads to an immediate crash to desktop when starting the app demo.

**Comment by gliheng** [comment]
Fixed
