### ISSUE TITLE
Would you support windows 10 desktop app?

### ISSUE THREAD

**Issue by chenjianxin** [gliheng/flutter-rs#5]
Would you plan to support windows 10 desktop app?

**Comment by gliheng** [comment]
Yes, I will work on it this month!

**Comment by chenshuiluke** [comment]
Thanks @gliheng !

**Comment by gliheng** [comment]
Hey, chenshuiluke. Now it should work on windows. I also updated flutter sdk to 1.2.1.   I'll add NSIS distribution sometime this week.
