### ISSUE TITLE
Contributing guideline

### ISSUE THREAD

**Issue by btwael** [gliheng/flutter-rs#6]
This is issue is for requesting a contributing guideline, mainly describing the source code structure and internal architecture of your work. Your work is very interesting in comparison with `flutter-desktop-embedding` and I would like to contribute!

**Comment by gliheng** [comment]
Hi, btwael. Thank you for your interest in this project. I added this [guideline](https://github.com/gliheng/flutter-rs/blob/master/CONTRIBUTING.md). I also updated some comment in the code. Hopeful that helps.
