### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by foxjazz** [gliheng/flutter-rs#61]
ubuntu subsystem or on windows build fails with:

error: failed to run custom build command for `glfw-sys v3.3.0`

Caused by:
  process didn't exit successfully: `G:\rust\flutter-rs\target\debug\build\glfw-sys-14aa8bdb431de969\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "C:\\Users\\fox21\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\glfw-sys-3.3.0\\." "-G" "Visual Studio 16 2019" "-Thost=x64" "-Ax64" "-DGLFW_BUILD_EXAMPLES=OFF" "-DGLFW_BUILD_TESTS=OFF" "-DGLFW_BUILD_DOCS=OFF" "-DCMAKE_INSTALL_LIBDIR=lib" "-DCMAKE_INSTALL_PREFIX=G:\\rust\\flutter-rs\\target\\debug\\build\\glfw-sys-dfa596fa242f662f\\out" "-DCMAKE_C_FLAGS= /nologo /MD" "-DCMAKE_C_FLAGS_DEBUG= /nologo /MD" "-DCMAKE_CXX_FLAGS= /nologo /MD" "-DCMAKE_CXX_FLAGS_DEBUG= /nologo /MD" "-DCMAKE_BUILD_TYPE=Debug"

--- stderr
thread 'main' panicked at '
failed to execute command: The system cannot find the file specified. (os error 2)
is `cmake` not installed?

build script failed, must exit now', C:\Users\fox21\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.39\src\lib.rs:829:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by gliheng** [comment]
cmake is needed for glfw-sys compilation on linux. Take a look here: https://github.com/PistonDevelopers/glfw-rs
But even if this succeeds, does WSL support linux GUI application?
