### ISSUE TITLE
It flash red when resize window on mac

### ISSUE THREAD

**Issue by wuapnjie** [gliheng/flutter-rs#67]
![Kapture 2019-08-30 at 16 47 47](https://user-images.githubusercontent.com/10895298/64007083-190de100-cb46-11e9-85ec-bde8c62972f7.gif)

**Comment by gliheng** [comment]
Thank you for your feedback. It's quite the same as https://github.com/gliheng/flutter-rs/issues/14 and I'll mark it as dup.

**Comment by wuapnjie** [comment]
Thank you
