### ISSUE TITLE
Possible to make the window borderless?

### ISSUE THREAD

**Issue by atresnjo** [gliheng/flutter-rs#7]
I'd love to test your project once it works on windows and also already have a use for it, do you know by any chance how hard it would be to make the window borderless? Thanks! 👍

**Comment by gliheng** [comment]
It's trivial to add support for borderless window mode. Glfw support various window hint to achive that. I've added to my todo list. Thank you for your suggestion.

**Comment by gliheng** [comment]
Hi, I added window_mode option in commit https://github.com/gliheng/flutter-rs/commit/1f51539cc36327fbe2496a20ff7d2bf9d030b47e  Now you can set Frameless window and FullScreen window.
